// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzzcgelcwwcalvjpqkpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6emNnZWxjd3djYWx2anBxa3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODUyOTksImV4cCI6MjA2NTQ2MTI5OX0.rT68XPX77sH11UZILkPzia6HLed9MAR0fMGYvkJf4GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);